# [Template] Builds and publishes UPM .tgz packages to pipeline artifacts

parameters:
  projectRoot: $(Get-Location)
  outputDirectory: $(Build.ArtifactStagingDirectory)\build\upm\output
  version: $(MRTKVersion)
  buildNumber: $(Build.BuildNumber)
  excludeBuildNumber: false

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.18.0'

- ${{ if eq(parameters.excludeBuildNumber, false) }}:
  - task: PowerShell@2
    displayName: 'Build PREVIEW UPM packages'
    inputs:
      targetType: filePath
      filePath: ./scripts/packaging/createupmpackages.ps1
      arguments: >
        -ProjectRoot ${{ parameters.projectRoot }}
        -OutputDirectory ${{ parameters.outputDirectory }}
        -Version ${{ parameters.version }}
        -BuildNumber ${{ parameters.buildNumber }}

- ${{ if eq(parameters.excludeBuildNumber, true) }}:
  - task: PowerShell@2
    displayName: 'Build OFFICIAL UPM packages'
    inputs:
      targetType: filePath
      filePath: ./scripts/packaging/createupmpackages.ps1
      arguments: >
        -ProjectRoot ${{ parameters.projectRoot }}
        -OutputDirectory ${{ parameters.outputDirectory }}
        -Version ${{ parameters.version }}
        -BuildNumber ${{ parameters.buildNumber }}
        -ExcludeBuildNumber

- task: PublishBuildArtifacts@1
  displayName: 'Publish UPM artifacts'
  inputs:
    PathtoPublish: ${{ parameters.outputDirectory }}
    ArtifactName: 'mrtk-upm'
