# Create UPM packages for public OFFICIAL release

variables:
- template: config/settings.yml

parameters:
- name: IsFinal
  type: boolean
  default: false
- name: BuildNumber
  type: string
  default: 0

jobs:
- job: UPMPublicRelease
  timeoutInMinutes: 30
  pool:
    vmImage: windows-2019
  steps:
  - template: templates/tasks/pack-upm.yml
    parameters:
      excludeBuildNumber: ${{ parameters.IsFinal }}
      buildNumber: ${{ parameters.BuildNumber }}
